# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Bilgisayar\4\1\son\process.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import matplotlib.pyplot as plt
from PyQt5.QtGui import QImage
from skimage import data, io, metrics
import skimage.exposure as skie
from skimage.transform import swirl
from cv2 import cv2
import imutils, sys
from PIL import Image
from skimage.morphology import square, closing
from skimage.color import rgb2gray
import numpy as np
from skimage.color import rgb2gray
from skimage.filters import gaussian
from skimage.util import random_noise

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 574)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 160, 132, 255), stop:1 rgba(255, 255, 255, 255));")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setObjectName("open")
        self.horizontalLayout_2.addWidget(self.open)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setObjectName("save")
        self.horizontalLayout_2.addWidget(self.save)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Info = QtWidgets.QLabel(self.centralwidget)
        self.Info.setObjectName("Info")
        self.horizontalLayout_2.addWidget(self.Info)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout.addWidget(self.resetButton, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.histButton = QtWidgets.QPushButton(self.centralwidget)
        self.histButton.setEnabled(True)
        self.histButton.setMinimumSize(QtCore.QSize(75, 0))
        self.histButton.setObjectName("histButton")
        self.verticalLayout.addWidget(self.histButton)
        self.sharpenButton = QtWidgets.QPushButton(self.centralwidget)
        self.sharpenButton.setMinimumSize(QtCore.QSize(75, 0))
        self.sharpenButton.setObjectName("sharpenButton")
        self.verticalLayout.addWidget(self.sharpenButton)
        self.restoration = QtWidgets.QPushButton(self.centralwidget)
        self.restoration.setObjectName("restoration")
        self.verticalLayout.addWidget(self.restoration)
        self.opening = QtWidgets.QPushButton(self.centralwidget)
        self.opening.setObjectName("opening")
        self.verticalLayout.addWidget(self.opening)
        self.closing = QtWidgets.QPushButton(self.centralwidget)
        self.closing.setObjectName("closing")
        self.verticalLayout.addWidget(self.closing)
        self.gaussianBlurButton = QtWidgets.QPushButton(self.centralwidget)
        self.gaussianBlurButton.setMinimumSize(QtCore.QSize(75, 0))
        self.gaussianBlurButton.setObjectName("gaussianBlurButton")
        self.verticalLayout.addWidget(self.gaussianBlurButton)
        self.genislemeButton = QtWidgets.QPushButton(self.centralwidget)
        self.genislemeButton.setObjectName("genislemeButton")
        self.verticalLayout.addWidget(self.genislemeButton)
        self.erosionButton = QtWidgets.QPushButton(self.centralwidget)
        self.erosionButton.setObjectName("erosionButton")
        self.verticalLayout.addWidget(self.erosionButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.goruntuLabel = QtWidgets.QLabel(self.centralwidget)
        self.goruntuLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.goruntuLabel.setObjectName("goruntuLabel")
        self.horizontalLayout_3.addWidget(self.goruntuLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.verticalLayout_2.addWidget(self.verticalSlider_2, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalLayout_2.addWidget(self.verticalSlider, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.save.clicked.connect(self.savePhoto)
        self.open.clicked.connect(self.loadImage)
        self.verticalSlider.valueChanged['int'].connect(self.brightness_value)
        self.verticalSlider_2.valueChanged['int'].connect(self.blur_value)
        self.histButton.clicked.connect(self.hist)
        self.resetButton.clicked.connect(self.reset)
        self.sharpenButton.clicked.connect(self.contrast)
        self.gaussianBlurButton.clicked.connect(self.gaussianBlur)
        self.erosionButton.clicked.connect(self.erosionImage)
        self.genislemeButton.clicked.connect(self.dilateImage)
        self.restoration.clicked.connect(self.Restoration)
        self.opening.clicked.connect(self.Opening)
        self.closing.clicked.connect(self.Closing)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Processing Project"))
        self.open.setText(_translate("MainWindow", "Open"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.Info.setText(_translate("MainWindow", "Info"))
        self.resetButton.setText(_translate("MainWindow", "RESET"))
        self.histButton.setText(_translate("MainWindow", "Histogram"))
        self.sharpenButton.setText(_translate("MainWindow", "Contrast"))
        self.restoration.setText(_translate("MainWindow", "Restoration"))
        self.opening.setText(_translate("MainWindow", "Opening"))
        self.closing.setText(_translate("MainWindow", "Closing"))
        self.gaussianBlurButton.setText(_translate("MainWindow", "Gaussian Blur"))
        self.genislemeButton.setText(_translate("MainWindow", "Dilation"))
        self.erosionButton.setText(_translate("MainWindow", "Erosion"))
        self.goruntuLabel.setText(_translate("MainWindow", "Photo"))
        self.label_3.setText(_translate("MainWindow", "Blur"))
        self.label_2.setText(_translate("MainWindow", "Brightness"))

# Added code here
        self.filename = None # Will hold the image address location
        self.tmp = None # Will hold the temporary image for display
        self.brightness_value_now = 0 # Updated brightness value
        self.blur_value_now = 0 # Updated blur value


    def loadImage(self):
        """ This function will load the user selected image
            and set it to label using the setPhoto function
        """
        self.filename = QFileDialog.getOpenFileName(filter="Image (*.*)")[0]
        if(self.filename):
            self.image = cv2.imread(self.filename)
            dim = str(self.image.shape)
            self.width, self.height = Image.open(self.filename).size
            self.width = str(self.width)
            self.height = str(self.height)
            info = dim + "(" + self.width + "x" + self.height + ")"
            self.Info.setText(info)
            self.setPhoto(self.image)

    def setPhoto(self,image):
        """ This function will take image input and resize it 
            only for display purpose and convert it to QImage
            to set at the label.
        """
        self.tmp = image
        #image = imutils.resize(image,width=320)
        frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = QImage(frame, frame.shape[1],frame.shape[0],frame.strides[0],QImage.Format_RGB888)
        self.goruntuLabel.setPixmap(QtGui.QPixmap.fromImage(image))

    def savePhoto(self):
        """ This function will save the image"""

        filename = QFileDialog.getSaveFileName(filter="JPG(*.jpg);;PNG(*.png);;TIFF(*.tiff);;BMP(*.bmp)")[0]
        if(filename):
            cv2.imwrite(filename,self.tmp)
            print('Image saved as:',self.filename)


    def brightness_value(self,value):
        """ This function will take value from the slider
            for the brightness from 0 to 99
        """
        self.brightness_value_now = value
        print('Brightness: ',value)
        self.update()
        
    def blur_value(self,value):
        """ This function will take value from the slider 
            for the blur from 0 to 99 """
        self.blur_value_now = value
        print('Blur: ',value)
        self.update()

    def update(self):
        """ This function will update the photo according to the 
            current values of blur and brightness and set it to photo label.
        """
        if self.tmp is not None:
            img = self.changeBrightness(self.image, self.brightness_value_now)
            img = self.changeBlur(img,self.blur_value_now)
            self.setPhoto(img)

    def changeBrightness(self,img,value):
        """ This function will take an image (img) and the brightness
            value. It will perform the brightness change using OpenCv
            and after split, will merge the img and return it.
        """
        hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
        h,s,v = cv2.split(hsv)
        lim = 255 - value
        v[v>lim] = 255
        v[v<=lim] += value
        final_hsv = cv2.merge((h,s,v))
        img = cv2.cvtColor(final_hsv,cv2.COLOR_HSV2BGR)
        return img
            
    def changeBlur(self,img,value):
        """ This function will take the img image and blur values as inputs.
            After perform blur operation using opencv function, it returns 
            the image img.
        """
        kernel_size = (value+1,value+1) # +1 is to avoid 0
        img = cv2.blur(img,kernel_size)
        return img


    def hist(self):
        if self.tmp is not None:
            img = cv2.cvtColor(self.tmp, cv2.COLOR_RGB2GRAY)
            img_hist = cv2.equalizeHist(img)
            self.setPhoto(img_hist)

    def reset(self):
        if self.tmp is not None:

            dim1 = len(self.image)
            print(dim1)
            dim2 = len(self.image[0])
            print(dim2)
            dim = str(self.image.shape)
            self.width = dim2
            self.height = dim1
            self.width = str(self.width)
            self.height = str(self.height)
            info = dim + "(" + self.width + "x" + self.height + ")"
            self.Info.setText(info)
            self.setPhoto(self.image)

    def contrast(self):
        if self.tmp is not None:
            sharpenKernel = np.array(([[0, -1, 0], [-1, 9, -1], [0, -1, 0]]), np.float32)/9
            sharpen = cv2.filter2D(src=self.tmp, kernel=sharpenKernel, ddepth=-1)
            self.setPhoto(sharpen)

    def gaussianBlur(self):
        '''
            Parameter	Description
            src	        input image
            dst	        output image
            ksize	    Gaussian Kernel Size. [height width]. height and width should be odd and can have different values. If ksize is set to [0 0], then ksize is computed from sigma values.
            sigmaX	    Kernel standard deviation along X-axis (horizontal direction).
            sigmaY	    Kernel standard deviation along Y-axis (vertical direction). If sigmaY=0, then sigmaX value is taken for sigmaY
            borderType	Specifies image boundaries while kernel is applied on image borders. Possible values are : cv.BORDER_CONSTANT cv.BORDER_REPLICATE cv.BORDER_REFLECT cv.BORDER_WRAP cv.BORDER_REFLECT_101 cv.BORDER_TRANSPARENT cv.BORDER_REFLECT101 cv.BORDER_DEFAULT cv.BORDER_ISOLATED
        '''
        if self.tmp is not None:
            gaussianBlurKernel = np.array(([[1, 2, 1], [2, 4, 2], [1, 2, 1]]), np.float32)/9
            gaussian = cv2.filter2D(src=self.tmp, kernel=gaussianBlurKernel, ddepth=-1)
            self.setPhoto(gaussian)

    def erosionImage(self):
        if self.tmp is not None:
            kernel = np.ones((3,3),np.uint8)
            erosion = cv2.erode(self.tmp,kernel,iterations = 1)
            self.setPhoto(erosion)

    def dilateImage(self):
        if self.tmp is not None:
            kernel = np.ones((5,5),np.uint8)
            dilation = cv2.dilate(self.tmp,kernel,iterations = 1)
            self.setPhoto(dilation)

    def Opening(self):
        if self.tmp is not None:
            kernel = np.ones((5,5),np.uint8)
            opening = cv2.morphologyEx(self.tmp, cv2.MORPH_OPEN, kernel)
            self.setPhoto(opening)

    def Closing(self):
        if self.tmp is not None:
            kernel = np.ones((5,5),np.uint8)
            closing = cv2.morphologyEx(self.tmp, cv2.MORPH_CLOSE, kernel)
            self.setPhoto(closing)

    def Restoration(self):
        if self.tmp is not None:
            sp_noise_image = random_noise(self.tmp, mode='s&p', amount =0.4)
            normal_noise_image = (255*sp_noise_image).astype(np.uint8)
            restoration = cv2.medianBlur(normal_noise_image, 3)
            SNR = metrics.peak_signal_noise_ratio(restoration, self.tmp)
            self.setPhoto(restoration)
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())